# Generated by Django 4.0.4 on 2022-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='motors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Brand')),
                ('model', models.CharField(max_length=250, verbose_name='Model')),
                ('photo', models.ImageField(upload_to='photos/%model/')),
                ('content', models.TextField(verbose_name='About')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motors',
            },
        ),
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
