# Generated by Django 4.0.4 on 2022-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_motors_alter_artiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'All News'},
        ),
        migrations.AlterModelOptions(
            name='motors',
            options={'ordering': ['title', 'model'], 'verbose_name': 'Motor', 'verbose_name_plural': 'Catalog of Motors'},
        ),
        migrations.AlterField(
            model_name='motors',
            name='photo',
            field=models.ImageField(upload_to='catalog/'),
        ),
    ]
