# Generated by Django 4.0.4 on 2022-06-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_artiles_options_alter_motors_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'ordering': ['-date'], 'verbose_name': 'New', 'verbose_name_plural': 'All News'},
        ),
    ]
